name: CLI Build 2 Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  workflow_dispatch: {}
  pull_request:

env:
  GO_VERSION: 1.18.1
  ARCH_AMD64: "amd64"
  GOOS_L: "linux"
  GOOS_W: "windows"
  GOOS_D: "darwin"
  RELEASE_VERSION: 1.0.0

jobs:
  cli-build-2-release:
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: |
          go version

      - name: Build CLI
        run: |
          chmod +x ci/build-cli.sh
          ci/build-cli.sh ${{ env.RELEASE_VERSION }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./bin/${{ env.ARCH_AMD64 }}-${{ env.GOOS_L }}-aws_cdk_poetry-${{ env.RELEASE_VERSION }}

      
      - name: Verify files
        run: |
          ls ./bin/${{ env.ARCH_AMD64 }}-${{ env.GOOS_L }}-aws_cdk_poetry* -l

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/${{ env.ARCH_AMD64 }}-${{ env.GOOS_L }}-aws_cdk_poetry-${{ env.RELEASE_VERSION }}
          tag_name: "v${{ env.RELEASE_VERSION }}" 
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

# if: startsWith(github.ref, 'refs/tags/')